name: core-ci

on:
  push:
  pull_request:

jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBRKBSC_BUILD_APP=OFF -DBRKBSC_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build -j2
      - name: Test
        run: ctest --test-dir build --output-on-failure
